# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_vin_DOC.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(526, 431)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 501, 408))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_47 = QtWidgets.QLabel(self.layoutWidget)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 13, 0, 1, 1)
        self.treapta_calitate = QtWidgets.QLineEdit(self.layoutWidget)
        self.treapta_calitate.setObjectName("treapta_calitate")
        self.gridLayout.addWidget(self.treapta_calitate, 6, 1, 3, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 3, 0, 1, 1)
        self.producator_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.producator_3.setObjectName("producator_3")
        self.gridLayout.addWidget(self.producator_3, 4, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.layoutWidget)
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 4, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget)
        self.label_46.setObjectName("label_46")
        self.gridLayout.addWidget(self.label_46, 5, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 11, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget)
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 1, 0, 1, 1)
        self.aspect_gustativ = QtWidgets.QLineEdit(self.layoutWidget)
        self.aspect_gustativ.setObjectName("aspect_gustativ")
        self.gridLayout.addWidget(self.aspect_gustativ, 12, 1, 1, 1)
        self.aspect_vizual = QtWidgets.QLineEdit(self.layoutWidget)
        self.aspect_vizual.setObjectName("aspect_vizual")
        self.gridLayout.addWidget(self.aspect_vizual, 14, 1, 1, 1)
        self.aspect_olfactiv = QtWidgets.QLineEdit(self.layoutWidget)
        self.aspect_olfactiv.setObjectName("aspect_olfactiv")
        self.gridLayout.addWidget(self.aspect_olfactiv, 13, 1, 1, 1)
        self.recipient_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.recipient_3.setObjectName("recipient_3")
        self.gridLayout.addWidget(self.recipient_3, 1, 3, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 6, 0, 3, 1)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget)
        self.label_49.setObjectName("label_49")
        self.gridLayout.addWidget(self.label_49, 15, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 16, 3, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget)
        self.label_48.setObjectName("label_48")
        self.gridLayout.addWidget(self.label_48, 14, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 4, 0, 1, 1)
        self.timp_decantare = QtWidgets.QLineEdit(self.layoutWidget)
        self.timp_decantare.setObjectName("timp_decantare")
        self.gridLayout.addWidget(self.timp_decantare, 0, 3, 1, 1)
        self.temperatura_servire = QtWidgets.QLineEdit(self.layoutWidget)
        self.temperatura_servire.setObjectName("temperatura_servire")
        self.gridLayout.addWidget(self.temperatura_servire, 15, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 16, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 12, 0, 1, 1)
        self.an_productie = QtWidgets.QLineEdit(self.layoutWidget)
        self.an_productie.setObjectName("an_productie")
        self.gridLayout.addWidget(self.an_productie, 5, 3, 1, 1)
        self.numar_unitati_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.numar_unitati_3.setObjectName("numar_unitati_3")
        self.gridLayout.addWidget(self.numar_unitati_3, 3, 3, 1, 1)
        self.pret_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.pret_3.setObjectName("pret_3")
        self.gridLayout.addWidget(self.pret_3, 4, 3, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 0, 0, 1, 1)
        self.volum_recipient_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.volum_recipient_2.setObjectName("volum_recipient_2")
        self.gridLayout.addWidget(self.volum_recipient_2, 2, 3, 1, 1)
        self.timp_pastrare = QtWidgets.QLineEdit(self.layoutWidget)
        self.timp_pastrare.setObjectName("timp_pastrare")
        self.gridLayout.addWidget(self.timp_pastrare, 6, 3, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget)
        self.label_51.setObjectName("label_51")
        self.gridLayout.addWidget(self.label_51, 1, 2, 1, 1)
        self.procent_alcool_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.procent_alcool_3.setText("")
        self.procent_alcool_3.setObjectName("procent_alcool_3")
        self.gridLayout.addWidget(self.procent_alcool_3, 9, 1, 1, 1)
        self.tara_origine_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.tara_origine_3.setObjectName("tara_origine_3")
        self.gridLayout.addWidget(self.tara_origine_3, 2, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 2, 0, 1, 1)
        self.soi_struguri_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.soi_struguri_3.setObjectName("soi_struguri_3")
        self.gridLayout.addWidget(self.soi_struguri_3, 1, 1, 1, 1)
        self.proces_producere = QtWidgets.QLineEdit(self.layoutWidget)
        self.proces_producere.setObjectName("proces_producere")
        self.gridLayout.addWidget(self.proces_producere, 5, 1, 1, 1)
        self.denumire_oc = QtWidgets.QLineEdit(self.layoutWidget)
        self.denumire_oc.setObjectName("denumire_oc")
        self.gridLayout.addWidget(self.denumire_oc, 0, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 10, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.layoutWidget)
        self.label_50.setObjectName("label_50")
        self.gridLayout.addWidget(self.label_50, 0, 2, 1, 1)
        self.culoare_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.culoare_3.setObjectName("culoare_3")
        self.gridLayout.addWidget(self.culoare_3, 11, 1, 1, 1)
        self.cantitate_zahar_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.cantitate_zahar_3.setObjectName("cantitate_zahar_3")
        self.gridLayout.addWidget(self.cantitate_zahar_3, 10, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget)
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 3, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget)
        self.label_45.setObjectName("label_45")
        self.gridLayout.addWidget(self.label_45, 9, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.layoutWidget)
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 2, 2, 1, 1)
        self.regiune = QtWidgets.QLineEdit(self.layoutWidget)
        self.regiune.setObjectName("regiune")
        self.gridLayout.addWidget(self.regiune, 3, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.layoutWidget)
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 5, 2, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.layoutWidget)
        self.label_56.setObjectName("label_56")
        self.gridLayout.addWidget(self.label_56, 6, 2, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.layoutWidget)
        self.label_57.setObjectName("label_57")
        self.gridLayout.addWidget(self.label_57, 8, 2, 1, 1)
        self.descriere_3 = QtWidgets.QTextEdit(self.layoutWidget)
        self.descriere_3.setObjectName("descriere_3")
        self.gridLayout.addWidget(self.descriere_3, 9, 2, 7, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_47.setText(_translate("Dialog", "Aspect olfactiv"))
        self.label_39.setText(_translate("Dialog", "Regiune"))
        self.label_54.setText(_translate("Dialog", "Pret"))
        self.label_46.setText(_translate("Dialog", "Proces producere"))
        self.label_43.setText(_translate("Dialog", "Culoare"))
        self.label_37.setText(_translate("Dialog", "Soi struguri"))
        self.label_41.setText(_translate("Dialog", "Treapta calitate"))
        self.label_49.setText(_translate("Dialog", "Temperatura servire"))
        self.pushButton_10.setText(_translate("Dialog", "Insert in DB"))
        self.label_48.setText(_translate("Dialog", "Aspect vizual"))
        self.label_40.setText(_translate("Dialog", "Producator"))
        self.pushButton_13.setText(_translate("Dialog", "Clear"))
        self.label_44.setText(_translate("Dialog", "Aspect gustativ"))
        self.label_36.setText(_translate("Dialog", "Denumire OC"))
        self.label_51.setText(_translate("Dialog", "Recipient"))
        self.label_38.setText(_translate("Dialog", "Tara origine"))
        self.label_42.setText(_translate("Dialog", "Cantitate zahar"))
        self.label_50.setText(_translate("Dialog", "Timp decantare"))
        self.label_53.setText(_translate("Dialog", "Numar unitati"))
        self.label_45.setText(_translate("Dialog", "Procent alcool"))
        self.label_52.setText(_translate("Dialog", "Volum recipient"))
        self.label_55.setText(_translate("Dialog", "An productie"))
        self.label_56.setText(_translate("Dialog", "Timp pastrare"))
        self.label_57.setText(_translate("Dialog", "Descriere"))

