# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_vin_regiune.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(515, 312)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 492, 285))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_65 = QtWidgets.QLabel(self.layoutWidget)
        self.label_65.setObjectName("label_65")
        self.gridLayout.addWidget(self.label_65, 0, 0, 1, 1)
        self.denumire_generica_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.denumire_generica_2.setObjectName("denumire_generica_2")
        self.gridLayout.addWidget(self.denumire_generica_2, 0, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.layoutWidget)
        self.label_73.setObjectName("label_73")
        self.gridLayout.addWidget(self.label_73, 1, 0, 1, 1)
        self.soi_struguri_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.soi_struguri_4.setObjectName("soi_struguri_4")
        self.gridLayout.addWidget(self.soi_struguri_4, 1, 1, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.layoutWidget)
        self.label_68.setObjectName("label_68")
        self.gridLayout.addWidget(self.label_68, 2, 0, 1, 1)
        self.tara_origine_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.tara_origine_4.setObjectName("tara_origine_4")
        self.gridLayout.addWidget(self.tara_origine_4, 2, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.layoutWidget)
        self.label_69.setObjectName("label_69")
        self.gridLayout.addWidget(self.label_69, 3, 0, 1, 1)
        self.zona_geografica_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.zona_geografica_2.setObjectName("zona_geografica_2")
        self.gridLayout.addWidget(self.zona_geografica_2, 3, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 10, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 10, 3, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.layoutWidget)
        self.label_67.setObjectName("label_67")
        self.gridLayout.addWidget(self.label_67, 4, 0, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.layoutWidget)
        self.label_66.setObjectName("label_66")
        self.gridLayout.addWidget(self.label_66, 5, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.layoutWidget)
        self.label_61.setObjectName("label_61")
        self.gridLayout.addWidget(self.label_61, 6, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.layoutWidget)
        self.label_62.setObjectName("label_62")
        self.gridLayout.addWidget(self.label_62, 7, 0, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.layoutWidget)
        self.label_58.setObjectName("label_58")
        self.gridLayout.addWidget(self.label_58, 8, 0, 1, 1)
        self.producator_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.producator_4.setObjectName("producator_4")
        self.gridLayout.addWidget(self.producator_4, 4, 1, 1, 1)
        self.procent_alcool_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.procent_alcool_4.setObjectName("procent_alcool_4")
        self.gridLayout.addWidget(self.procent_alcool_4, 5, 1, 1, 1)
        self.cantitate_zahar_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.cantitate_zahar_4.setObjectName("cantitate_zahar_4")
        self.gridLayout.addWidget(self.cantitate_zahar_4, 6, 1, 1, 1)
        self.culoare_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.culoare_4.setObjectName("culoare_4")
        self.gridLayout.addWidget(self.culoare_4, 7, 1, 1, 1)
        self.recipient_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.recipient_4.setObjectName("recipient_4")
        self.gridLayout.addWidget(self.recipient_4, 8, 1, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.layoutWidget)
        self.label_72.setObjectName("label_72")
        self.gridLayout.addWidget(self.label_72, 9, 0, 1, 1)
        self.volum_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.volum_2.setObjectName("volum_2")
        self.gridLayout.addWidget(self.volum_2, 9, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.layoutWidget)
        self.label_64.setObjectName("label_64")
        self.gridLayout.addWidget(self.label_64, 0, 2, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.layoutWidget)
        self.label_60.setObjectName("label_60")
        self.gridLayout.addWidget(self.label_60, 1, 2, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.layoutWidget)
        self.label_70.setObjectName("label_70")
        self.gridLayout.addWidget(self.label_70, 2, 2, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.layoutWidget)
        self.label_63.setObjectName("label_63")
        self.gridLayout.addWidget(self.label_63, 3, 2, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.layoutWidget)
        self.label_59.setObjectName("label_59")
        self.gridLayout.addWidget(self.label_59, 4, 2, 1, 1)
        self.numar_unitati_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.numar_unitati_4.setObjectName("numar_unitati_4")
        self.gridLayout.addWidget(self.numar_unitati_4, 0, 3, 1, 1)
        self.pret_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.pret_4.setObjectName("pret_4")
        self.gridLayout.addWidget(self.pret_4, 1, 3, 1, 1)
        self.an_productie = QtWidgets.QLineEdit(self.layoutWidget)
        self.an_productie.setObjectName("an_productie")
        self.gridLayout.addWidget(self.an_productie, 2, 3, 1, 1)
        self.timp_pastrare = QtWidgets.QLineEdit(self.layoutWidget)
        self.timp_pastrare.setObjectName("timp_pastrare")
        self.gridLayout.addWidget(self.timp_pastrare, 3, 3, 1, 1)
        self.descriere_4 = QtWidgets.QTextEdit(self.layoutWidget)
        self.descriere_4.setObjectName("descriere_4")
        self.gridLayout.addWidget(self.descriere_4, 5, 2, 5, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_65.setText(_translate("Dialog", "Denumire generica"))
        self.label_73.setText(_translate("Dialog", "Soi struguri"))
        self.label_68.setText(_translate("Dialog", "Tara origine"))
        self.label_69.setText(_translate("Dialog", "Zona geografica"))
        self.pushButton_14.setText(_translate("Dialog", "Clear"))
        self.pushButton_15.setText(_translate("Dialog", "Insert in DB"))
        self.label_67.setText(_translate("Dialog", "Producator"))
        self.label_66.setText(_translate("Dialog", "Procent alcool"))
        self.label_61.setText(_translate("Dialog", "Cantitate zahar"))
        self.label_62.setText(_translate("Dialog", "Culoare"))
        self.label_58.setText(_translate("Dialog", "Recipient"))
        self.label_72.setText(_translate("Dialog", "Volum"))
        self.label_64.setText(_translate("Dialog", "Numar unitati"))
        self.label_60.setText(_translate("Dialog", "Pret"))
        self.label_70.setText(_translate("Dialog", "An productie"))
        self.label_63.setText(_translate("Dialog", "Timp pastrare"))
        self.label_59.setText(_translate("Dialog", "Descriere"))

