# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_vin_masa.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(504, 305)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 478, 285))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.denumire = QtWidgets.QLineEdit(self.layoutWidget)
        self.denumire.setObjectName("denumire")
        self.gridLayout.addWidget(self.denumire, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 2, 1, 1)
        self.pret = QtWidgets.QLineEdit(self.layoutWidget)
        self.pret.setObjectName("pret")
        self.gridLayout.addWidget(self.pret, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.soi_struguri = QtWidgets.QLineEdit(self.layoutWidget)
        self.soi_struguri.setObjectName("soi_struguri")
        self.gridLayout.addWidget(self.soi_struguri, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 2, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.tara_origine = QtWidgets.QLineEdit(self.layoutWidget)
        self.tara_origine.setObjectName("tara_origine")
        self.gridLayout.addWidget(self.tara_origine, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 2, 2, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.producator = QtWidgets.QLineEdit(self.layoutWidget)
        self.producator.setObjectName("producator")
        self.gridLayout.addWidget(self.producator, 3, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 3, 2, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.procent_alcool = QtWidgets.QLineEdit(self.layoutWidget)
        self.procent_alcool.setObjectName("procent_alcool")
        self.gridLayout.addWidget(self.procent_alcool, 4, 1, 1, 1)
        self.descriere = QtWidgets.QTextEdit(self.layoutWidget)
        self.descriere.setObjectName("descriere")
        self.gridLayout.addWidget(self.descriere, 4, 2, 6, 3)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.cantitate_zahar = QtWidgets.QLineEdit(self.layoutWidget)
        self.cantitate_zahar.setObjectName("cantitate_zahar")
        self.gridLayout.addWidget(self.cantitate_zahar, 5, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.culoare = QtWidgets.QLineEdit(self.layoutWidget)
        self.culoare.setObjectName("culoare")
        self.gridLayout.addWidget(self.culoare, 6, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 7, 0, 1, 1)
        self.recipient = QtWidgets.QLineEdit(self.layoutWidget)
        self.recipient.setObjectName("recipient")
        self.gridLayout.addWidget(self.recipient, 7, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 8, 0, 1, 1)
        self.volum_recipient = QtWidgets.QLineEdit(self.layoutWidget)
        self.volum_recipient.setObjectName("volum_recipient")
        self.gridLayout.addWidget(self.volum_recipient, 8, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 9, 0, 1, 1)
        self.numar_unitati = QtWidgets.QLineEdit(self.layoutWidget)
        self.numar_unitati.setObjectName("numar_unitati")
        self.gridLayout.addWidget(self.numar_unitati, 9, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 10, 3, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 10, 4, 1, 1)
        self.an_productie = QtWidgets.QLineEdit(self.layoutWidget)
        self.an_productie.setObjectName("an_productie")
        self.gridLayout.addWidget(self.an_productie, 1, 4, 1, 1)
        self.timp_pastrare = QtWidgets.QLineEdit(self.layoutWidget)
        self.timp_pastrare.setObjectName("timp_pastrare")
        self.gridLayout.addWidget(self.timp_pastrare, 2, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "Denumire"))
        self.label_16.setText(_translate("Dialog", "Pret"))
        self.label_7.setText(_translate("Dialog", "Soi struguri"))
        self.label_17.setText(_translate("Dialog", "An productie"))
        self.label_8.setText(_translate("Dialog", "Tara origine"))
        self.label_18.setText(_translate("Dialog", "Timp pastrare"))
        self.label_9.setText(_translate("Dialog", "Producator"))
        self.label_19.setText(_translate("Dialog", "Descriere"))
        self.label_10.setText(_translate("Dialog", "Procent alcool"))
        self.label_11.setText(_translate("Dialog", "Cantitate zahar"))
        self.label_12.setText(_translate("Dialog", "Culoare"))
        self.label_13.setText(_translate("Dialog", "Recipient"))
        self.label_14.setText(_translate("Dialog", "Volum recipient"))
        self.label_15.setText(_translate("Dialog", "Numar unitati"))
        self.pushButton_8.setText(_translate("Dialog", "Clear"))
        self.pushButton_11.setText(_translate("Dialog", "Save in DB"))

